stages:
  - terraform

terraform:
  stage: terraform
  image: hashicorp/terraform:latest
  script:
    - terraform init
    - terraform plan -out=tfplan
    - terraform apply -input=false tfplan
  only:
    - main
  variables:
    ARM_CLIENT_ID: $ARM_CLIENT_ID
    ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET
    ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID
    ARM_TENANT_ID: $ARM_TENANT_ID
