trigger_pipeline:
  script:
    - "curl -X POST --fail -F token=glptt-2002ca2b69e5ec91bd27d355211646614c750306 -F ref=main https://gitlab.com/api/v4/projects/47117778/trigger/pipeline"

stages:
  - terraform

terraform:
  stage: terraform
  image: hashicorp/terraform:latest
  script:
    - terraform init
    - terraform plan -out=tfplan
    - terraform apply -input=false tfplan
  only:
    - main
  variables:
    ARM_CLIENT_ID: $ARM_CLIENT_ID
    ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET
    ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID
    ARM_TENANT_ID: $ARM_TENANT_ID
