name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

env:
  TF_ENV: 'dev' # Default environment

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TF_ENV=prod" >> $GITHUB_ENV
          else
            echo "TF_ENV=dev" >> $GITHUB_ENV
          fi

      # SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=reddyfull
            -Dsonar.projectKey=reddyfull_learn_terraform

      - name: Set environment variables
        run: |
          echo "TF_VAR_subscription_id=${{ secrets['AZURE_SUBSCRIPTION_ID_' + env.TF_ENV] }}" >> $GITHUB_ENV
          echo "TF_VAR_tenant_id=${{ secrets['AZURE_TENANT_ID_' + env.TF_ENV] }}" >> $GITHUB_ENV
          echo "TF_VAR_client_id=${{ secrets['AZURE_CLIENT_ID_' + env.TF_ENV] }}" >> $GITHUB_ENV
          echo "TF_VAR_client_secret=${{ secrets['AZURE_CLIENT_SECRET_' + env.TF_ENV] }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

