name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

env:
  TF_ENV: 'prod' # Default environment

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TF_ENV=prod" >> $GITHUB_ENV
          else
            echo "TF_ENV=dev" >> $GITHUB_ENV
          fi

      # SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=reddyfull
            -Dsonar.projectKey=reddyfull_learn_terraform

      - name: Set environment-specific secrets
        id: set_secrets
        run: |
          if [[ "${{ env.TF_ENV }}" == "prod" ]]; then
            echo "::set-output name=SUBSCRIPTION_ID::${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}"
            echo "::set-output name=TENANT_ID::${{ secrets.AZURE_TENANT_ID_PROD }}"
            echo "::set-output name=CLIENT_ID::${{ secrets.AZURE_CLIENT_ID_PROD }}"
            echo "::set-output name=CLIENT_SECRET::${{ secrets.AZURE_CLIENT_SECRET_PROD }}"
          else
            echo "::set-output name=SUBSCRIPTION_ID::${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}"
            echo "::set-output name=TENANT_ID::${{ secrets.AZURE_TENANT_ID_DEV }}"
            echo "::set-output name=CLIENT_ID::${{ secrets.AZURE_CLIENT_ID_DEV }}"
            echo "::set-output name=CLIENT_SECRET::${{ secrets.AZURE_CLIENT_SECRET_DEV }}"
          fi

      - name: Set environment variables
        run: |
          echo "TF_VAR_subscription_id=${{ steps.set_secrets.outputs.SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_tenant_id=${{ steps.set_secrets.outputs.TENANT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_client_id=${{ steps.set_secrets.outputs.CLIENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_client_secret=${{ steps.set_secrets.outputs.CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
