name: Terraform Deployment

on:
  push:
    branches:
      - main

env:
  AZURE_RG_NAME: example-resource-group

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Az CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az --version

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure Azure credentials
      run: |
        echo ${{ secrets.AZURE_CREDENTIALS }} > azure_credentials.json

    - name: Log in to Azure
      run: |
        az login --service-principal --username ${{ secrets.CLIENT_ID }} --password ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
        az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}

    - name: Assign Owner role to resource group
      run: |
        az role assignment create --role "Owner" --assignee ${{ secrets.CLIENT_ID }} --scope /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ env.AZURE_RG_NAME }}

    - name: Set up Azure CLI
      run: az configure --defaults group=${{ env.AZURE_RG_NAME }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
