name: 'Terraform'

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

env:
  TF_ENV: "develop" # default to develop environment

jobs:
  sonarcloud_scan:
    name: 'SonarCloud Scan'
    runs-on: ubuntu-latest

    steps:
      - name: 'Task 1: Checkout'
        uses: actions/checkout@v2
        
      - name: 'Task 2: SonarCloud Scan'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=reddyfull
            -Dsonar.projectKey=reddyfull_learn_terraform

  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    needs: sonarcloud_scan

    steps:
      - name: 'Task 3: Setup environment'
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "TF_ENV=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "TF_ENV=main" >> $GITHUB_ENV
          fi

      - name: 'Task 4: Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: 'Task 5: Set environment variables'
        run: |
          echo "TF_VAR_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_tenant_id=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_client_id=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: 'Task 6: Terraform Initialize'
        run: terraform init

      - name: 'Task 7: Terraform Plan'
        run: terraform plan

      - name: 'Task 8: Terraform Apply'
        run: terraform apply -auto-approve
